services:
  api:
    image: t0mc4mp/harvesting.food.api:latest
    env_file:
      - ./prod.env
    ports:
      - "5100:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - uv
      - run
      - --no-dev
      - uvicorn
      - app.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --workers
      - "2"
    restart: unless-stopped
