"""add_archived_at_to_plant

Revision ID: 1bd2c21649eb
Revises: 39447d6cf8bf
Create Date: 2026-04-15 18:42:26.303979

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1bd2c21649eb'
down_revision: str | None = '39447d6cf8bf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'archived_at')
    # ### end Alembic commands ###
