"""add site invitation

Revision ID: 1c058908b8af
Revises: c2c37eb6898d
Create Date: 2026-05-12 20:47:14.062881

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1c058908b8af'
down_revision: str | None = 'c2c37eb6898d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siteinvitation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invited_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_siteinvitation_invited_email'), 'siteinvitation', ['invited_email'], unique=False)
    op.create_index(op.f('ix_siteinvitation_token'), 'siteinvitation', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_siteinvitation_token'), table_name='siteinvitation')
    op.drop_index(op.f('ix_siteinvitation_invited_email'), table_name='siteinvitation')
    op.drop_table('siteinvitation')
    # ### end Alembic commands ###
