"""changing more harvest to harvests

Revision ID: 39447d6cf8bf
Revises: 20b4bccb00fc
Create Date: 2026-04-12 19:09:17.182012

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '39447d6cf8bf'
down_revision: str | None = '20b4bccb00fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
