"""add latin_name to plant

Revision ID: 4ceb28f6e96b
Revises: 11985dfe433b
Create Date: 2026-04-11 20:24:02.102234

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4ceb28f6e96b'
down_revision: str | None = '11985dfe433b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('latin_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'latin_name')
    # ### end Alembic commands ###
