"""plant model rebuild

Revision ID: 4dd59d54847d
Revises: 3b52404a039a
Create Date: 2026-04-05 17:28:22.265114

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dd59d54847d'
down_revision: str | None = '3b52404a039a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('herb', 'vegetable', 'fruit', 'flower', 'shrub', 'tree', 'vine', name='planttype').create(op.get_bind(), checkfirst=True)
    op.create_table('careinfo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('planting', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('care', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('harvesting', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latin_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('garden', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('garden', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('plant', sa.Column('species', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('plant', sa.Column('planted_date', sa.DateTime(), nullable=True))
    op.alter_column('plant', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plant', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plant', 'plant_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('herb', 'vegetable', 'fruit', 'flower', 'shrub', 'tree', 'vine', name='planttype'),
               existing_nullable=False,
               postgresql_using='plant_type::text::planttype')
    op.drop_column('plant', 'notes')
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('plant', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('plant', 'plant_type',
               existing_type=sa.Enum('herb', 'vegetable', 'fruit', 'flower', 'shrub', 'tree', 'vine', name='planttype'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='plant_type::text')
    op.alter_column('plant', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('plant', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('plant', 'planted_date')
    op.drop_column('plant', 'species')
    op.alter_column('garden', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('garden', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table('note')
    op.drop_table('careinfo')
    sa.Enum(name='planttype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
