"""remove_google_sub

Revision ID: 55db8035bd95
Revises: 5e8236014c51
Create Date: 2026-04-06 20:27:11.243869

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '55db8035bd95'
down_revision: str | None = '5e8236014c51'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_google_sub'), table_name='user')
    op.drop_column('user', 'google_sub')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_sub', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_google_sub'), 'user', ['google_sub'], unique=True)
    # ### end Alembic commands ###
