"""remodel users and gardens with sharing

Revision ID: 5e8236014c51
Revises: 6fc8a132a243
Create Date: 2026-04-06 18:40:14.913486

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5e8236014c51'
down_revision: str | None = '6fc8a132a243'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gardeninvitation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('garden_id', sa.Uuid(), nullable=False),
    sa.Column('invited_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gardeninvitation_invited_email'), 'gardeninvitation', ['invited_email'], unique=False)
    op.create_index(op.f('ix_gardeninvitation_token'), 'gardeninvitation', ['token'], unique=True)
    op.create_table('gardenmember',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('garden_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='gardenmemberrole'), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garden_id', 'user_id')
    )
    op.add_column('garden', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('garden_name_key'), 'garden', type_='unique')
    op.drop_constraint(op.f('garden_user_id_key'), 'garden', type_='unique')
    op.create_index(op.f('ix_garden_user_id'), 'garden', ['user_id'], unique=False)
    op.add_column('user', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    sa.Enum('pending', 'active', 'suspended', name='userstatus').create(op.get_bind())
    sa.Enum('user', 'admin', name='userrole').create(op.get_bind())
    op.add_column('user', sa.Column('status', sa.Enum('pending', 'active', 'suspended', name='userstatus', create_type=False), nullable=False, server_default='pending'))
    op.add_column('user', sa.Column('role', sa.Enum('user', 'admin', name='userrole', create_type=False), nullable=False, server_default='user'))
    op.alter_column('user', 'google_sub',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('user', 'google_sub',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'role')
    op.drop_column('user', 'status')
    sa.Enum(name='userrole').drop(op.get_bind())
    sa.Enum(name='userstatus').drop(op.get_bind())
    op.drop_column('user', 'password_hash')
    op.drop_index(op.f('ix_garden_user_id'), table_name='garden')
    op.create_unique_constraint(op.f('garden_user_id_key'), 'garden', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('garden_name_key'), 'garden', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('garden', 'location')
    op.drop_table('gardenmember')
    op.drop_index(op.f('ix_gardeninvitation_token'), table_name='gardeninvitation')
    op.drop_index(op.f('ix_gardeninvitation_invited_email'), table_name='gardeninvitation')
    op.drop_table('gardeninvitation')
    # ### end Alembic commands ###
