"""slugifying gardens

Revision ID: 6fc8a132a243
Revises: b0fc69ead575
Create Date: 2026-04-05 20:18:15.072424

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6fc8a132a243'
down_revision: str | None = 'b0fc69ead575'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garden', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_garden_slug'), 'garden', ['slug'], unique=True)
    op.create_unique_constraint(None, 'garden', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'garden', type_='unique')
    op.drop_index(op.f('ix_garden_slug'), table_name='garden')
    op.drop_column('garden', 'slug')
    # ### end Alembic commands ###
