"""add changing harvest model

Revision ID: 8bbb59c668c3
Revises: 4ceb28f6e96b
Create Date: 2026-04-12 14:13:43.235985

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8bbb59c668c3'
down_revision: str | None = '4ceb28f6e96b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


unittype = sa.Enum('items', 'g', 'kg', 'oz', 'lb', 'bunches', 'bags', 'jars', 'other', name='unittype')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    unittype.create(op.get_bind(), checkfirst=True)
    op.add_column('harvest', sa.Column('amount', sa.Integer(), nullable=True))
    op.execute("UPDATE harvest SET amount = 0 WHERE amount IS NULL")
    op.alter_column('harvest', 'amount', nullable=False)
    op.add_column('harvest', sa.Column('unit', unittype, nullable=True))
    op.drop_column('harvest', 'weight')
    op.drop_column('harvest', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvest', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('harvest', sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('harvest', 'unit')
    op.drop_column('harvest', 'amount')
    unittype.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
