"""fix planttype enum values

Revision ID: b0fc69ead575
Revises: 7a047f1de9f9
Create Date: 2026-04-05 18:32:50.686758

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0fc69ead575'
down_revision: str | None = '7a047f1de9f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant', 'plant_type',
               existing_type=postgresql.ENUM('herb', 'vegetable', 'fruit', 'flower', 'shrub', 'tree', 'vine', name='planttype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant', 'plant_type',
               existing_type=postgresql.ENUM('herb', 'vegetable', 'fruit', 'flower', 'shrub', 'tree', 'vine', name='planttype'),
               nullable=False)
    # ### end Alembic commands ###
