"""add harvest_unit to plant

Revision ID: c8774ee75093
Revises: 8bbb59c668c3
Create Date: 2026-04-12 16:53:32.083958

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c8774ee75093'
down_revision: str | None = '8bbb59c668c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('harvest_unit', sa.Enum('items', 'g', 'kg', 'oz', 'lb', 'bunches', 'bags', 'jars', 'other', name='unittype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'harvest_unit')
    # ### end Alembic commands ###
