"""add first_login and last_login to user

Revision ID: e21917a802b8
Revises: 86e5875e913e
Create Date: 2026-07-04 13:20:30.715927

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e21917a802b8'
down_revision: str | None = '86e5875e913e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'first_login')
    # ### end Alembic commands ###
